create table orders (
   orderId integer generated by default as identity (start with 1000) not null,
   date timestamp not null,
   customer varchar(255) not null,
   constraint pk_orders primary key (orderId),
   constraint fk_orders_customers foreign key (customer) references customers(username)
);